/**
 * Agent Types
 * All types related to AI agents
 */

// Agent Status
export type AgentStatus = 'creating' | 'ready' | 'training' | 'error'

// Agent Model Options
export type AgentModel = 'gpt-3.5-turbo' | 'gpt-4' | 'gpt-4-turbo'

// Base Agent Type
export type Agent = {
  _id: string
  name: string
  description?: string
  systemPrompt: string
  temperature: number
  model: AgentModel
  status: AgentStatus
  avatar?: string
  maxTokens?: number
  topP?: number
  frequencyPenalty?: number
  presencePenalty?: number
  isPublic?: boolean
  tags?: string[]
  metadata?: {
    totalSessions?: number
    totalMessages?: number
    lastUsed?: string
  }
  trainedAt?: string
  lastUsed?: string
  createdAt: string
  updatedAt: string
  companyId?: string
  userId?: string
  __v?: number
}

// Agent Creation Payload
export type CreateAgentPayload = {
  _id?: string // Optional ID - will be generated by frontend if not provided
  name: string
  description?: string
  systemPrompt: string
  temperature: number
  model: AgentModel
}

// Agent Update Payload
export type UpdateAgentPayload = Partial<Omit<Agent, '_id' | 'createdAt' | 'updatedAt'>>

// Agent Statistics
export type AgentStats = {
  totalAgents: number
  totalSessions: number
  totalMessages: number
  totalFiles: number
}

// Agent Model Configuration
export type AgentModelConfig = {
  id: AgentModel
  name: string
  description: string
  maxTokens?: number
  costPer1k?: number
}
